// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // `prisma migrate dev` needs a second, throwaway database to detect drift.
    // `npx prisma dev` provides one; hosted Postgres usually does not, in which
    // case leave this unset and Prisma creates a temporary one itself.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
